
server:
  port: 8081
camunda:
  bpm:    
    authorization:
      enabled: true
    admin-user:
      id: admin
      password: password
      firstName: admin      
    filter:
      create: All tasks

config-user:
  add-basic-user: true
  run-sample-flow: true


